apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tools
  name: mongodb-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
  requests:
  storage: 2Gi
  storageClassName: hostpath
